blank_issues_enabled: false
contact_links:
  - name: Support
    url: https://github.com/thomas-carter-aic/thomas-carter-aic.github.io/discussions
    about: Please post your support questions in the Discussions section.